<?php

return [
        'admin'=> ['admin','admins','all admins','all admin','new admin','new admins','depot manager','org admin','organization admin','view admin','view admins','view all admins','view all admin','list of admins','list of all admins','deactivate admin','activate admin'],
		'employee'=> ['type of employee','employee','employees','list of employee','all employee','all employees','new employee', 'view employee', 'view employees','list of all employees', 'contract employees', 'permanent employees','deactivate employee','activate employee'],
		'authorization'=> ['authorization','authorizations','create new authorizations','create authorization','new authorization','view authorizations','list of all authorizations'],
		'screen'=> ['screen','screens','all screens','create new screen','create screen','view screen','list of screens','update screens','deactivate screen','activate screen'],
		'module'=> ['module','modules','all modules','create new module','create module','view module','list of modules','update modules','deactivate module','activate module'],
		'role'=> ['role','create role','view role','list of roles','all roles','create new role'],
		'assign_role'=> ['assign role','new role','give role','assign role to employee', 'give role to employee','employee roles','role of employees'],
		'customer'=> ['view customer','customers','all customers','list of customers','deactivate customer','activate customer'],
		'assign_customer'=> ['assign customer','assign customers','assign cutomer to employee','give customer to employee','assign farmer to employee','assign retailer to employee'],
		'my_customer'=> ['my customer','my customers','view my customers','list of my customers'],
		'create_farmer'=> ['create farmer','create farmers','create new farmer','upload farmers'],
		'create_reatiler'=> ['create retailer','create retailers','create new retailer','upload retailers'],
		'stock'=> ['new stock','stock','stocks','view stock','list of stocks','all stocks'],
		'order'=> ['order','orders','view order','list of orders','all orders','new order'],
		'packaging_unit'=> ['packaging unit','packaging units','view packaging unit','list of packaging units','all packaging units','new packaging unit'],
		'plant'=> ['plant','plants','view plant','list of plants','all plants','new plant'],
		'my_order'=> ['my order','my orders','view my order','list of my orders'],
		'material'=> ['material','material group','view material groups','list of material groups','all material groups','new material group','material groups'],
		'create_claim'=> ['create claims','create new claim','create my claim','new claim','create claim'],
		'view_claim'=> ['view claim','my claim','my claims','view my claims','list of my claims','my pending claims'],
		'approve_claim'=> ['approve claim','approve claims','list of all claims','approve pending claims','list of approved claims','list of rejected claims'],
		'level_settings'=> ['create level','level settings','change level expenses','global days settings','change global settings','change level settings','configurations','settings','global settings'],
		'level_view'=> ['view level','levels','level','list of levels','all levels','employee levels','update employee level','change level','change employee level'],
		'contact'=> ['org chart','contact in a level','all contacts'],
		'contacts'=> ['contact','contacts','my contacts'],
		'my_ticket'=> ['my ticket','my tickets','view my ticket','list of my tickets','respond to my ticket'],
		'ticket'=> ['ticket','tickets','all tickets','list of tickets'],
		'open_ticket'=> ['assigned ticket','ticket response','respond to ticket','tickets assigned to me','assigned tickets'],
		'announce'=> ['announcement','type of nnouncement','announcement type','create announcement type'],
		'create_announce'=> ['create announcement','view announcement','list of announcements','all announcements'],
		'my_announce'=> ['my announcement','my announcements','view my announcement','list of my announcements'],
		'create_employee'=> ['create employee','create employees','create new employee','upload employees'],
		'myregionorder'=> ['my region orders','orders in my region','orders of my region','my region order'],
		'my_plant'=> ['my plants','plants in my region','plants of my region','my plant', 'view my plants','list of my plants'],
		'my_stock'=> ['my stocks','stocks in my region','stocks of my region','my stock', 'view my stocks','list of my stocks'],
		'dashboard'=> ['my home','home page', 'dashboard','view dashboard', 'return to home','return to dashboard'],
		'profile'=> ['my profile','edit profile', 'change profile pic','change my mobile number', 'change password','change profile photo','view my details','view my profile','edit my profile','change my profile'],
		'verify_dist'=> ['verify distributors','verify new distributors', 'verify distributor','verify new distributor', 'change distributor','change new distributor'],
		'rejected_claim'=> ['rejected claims','mark void claim', 'rejected claims of employees','mark void rejected claims', 'delete rejected claim','undo rejected claim'],
		'create_comp'=> ['create ticket component','view ticket component', 'ticket component','ticket components', 'all ticket components','list of ticket components'],
		'assign_comp'=> ['assign ticket component','assign component to processor', 'assign ticket processor','create component processor', 'create new component processor','assign ticket processor'],
		'area'=> ['create area','create areas', 'view area','view all areas', 'all areas','add new area'],
		'zone'=> ['create zone','create zones', 'view zone','view all zones', 'all zones','add new zone'],
		'assign_plant'=> ['assign region','assign regions', 'assign region to employee','assign region to employees', 'change region of employee','update region of employee'],
		'depot_order'=> ['depot order','depot orders', 'list of depot orders','order created by depot', 'download depot orders','all depot orders'],
		'task'=> ['my task','all tasks', 'list of tasks','my tasks', 'task created by me','all task'],
		'assigned_task'=> ['assigned task','my assigned task', 'my assigned tasks','assigned tasks', 'list of tasks assigned to me','task assigned to me'],
		'delegated_task'=> ['delegated task','my delegated task', 'my delegated tasks','delegated tasks', 'list of tasks delegated to me','task delegated to me']

];
